esprit_dhawdhaw:
    resource: "@EspritDhawdhawBundle/Resources/config/routing.yml"
    prefix:   /

dhia:
    resource: "@DhiaBundle/Resources/config/routing.xml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
